import React, { useState, useMemo } from "react";
import {
  ClipboardList,
  Plus,
  AlertTriangle,
  Clock,
  Plane,
  Wrench,
  Shirt,
  MoreHorizontal,
  Check,
  Trash2,
  X,
  LogIn,
  LogOut,
  Sparkles,
  CheckSquare,
  Cpu,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useHostel } from "../HostelContext";
import { useTranslation } from "../i18nContext";
import { useStaff } from "../StaffContext";
import { formatDistanceToNow, parseISO } from "date-fns";
import { ShiftNoteCategory, ShiftNoteSource, ShiftNote } from "../types";

const categoryIcons: Record<ShiftNoteCategory, React.ElementType> = {
  general: ClipboardList,
  "late-arrival": Plane,
  maintenance: Wrench,
  pickup: Clock,
  laundry: Shirt,
  other: MoreHorizontal,
};

const categoryColors: Record<ShiftNoteCategory, string> = {
  general: "text-muted-foreground bg-zinc-100",
  "late-arrival": "text-amber-600 bg-amber-50",
  maintenance: "text-red-500 bg-red-50",
  pickup: "text-blue-500 bg-blue-50",
  laundry: "text-purple-500 bg-purple-50",
  other: "text-muted-foreground bg-zinc-100",
};

const categoryBorderColors: Record<ShiftNoteCategory, string> = {
  general: "border-l-zinc-400",
  "late-arrival": "border-l-amber-400",
  maintenance: "border-l-red-400",
  pickup: "border-l-blue-400",
  laundry: "border-l-purple-400",
  other: "border-l-zinc-400",
};

const categoryI18nKeys: Record<ShiftNoteCategory, string> = {
  general: "shiftlog.general",
  "late-arrival": "shiftlog.lateArrival",
  maintenance: "shiftlog.maintenance",
  pickup: "shiftlog.pickup",
  laundry: "shiftlog.laundry",
  other: "shiftlog.other",
};

const sourceIcons: Record<ShiftNoteSource, { icon: React.ElementType; className: string }> = {
  manual: { icon: ClipboardList, className: "bg-zinc-100 text-zinc-600" },
  checkin: { icon: LogIn, className: "bg-emerald-50 text-emerald-700" },
  checkout: { icon: LogOut, className: "bg-orange-50 text-orange-700" },
  cleaning: { icon: Sparkles, className: "bg-purple-50 text-purple-700" },
  system: { icon: Cpu, className: "bg-zinc-100 text-muted-foreground" },
};

const sourceI18nKeys: Record<ShiftNoteSource, string> = {
  manual: "shiftlog.manual",
  checkin: "shiftlog.sourceCheckin",
  checkout: "shiftlog.sourceCheckout",
  cleaning: "shiftlog.sourceCleaning",
  system: "shiftlog.sourceSystem",
};

type FilterType = "all" | "unresolved" | "urgent" | "manual" | "auto" | ShiftNoteCategory;

interface ShiftLogProps {
  onNavigate?: (tab: string) => void;
}

export function ShiftLog({ onNavigate }: ShiftLogProps) {
  const { shiftNotes, addShiftNote, resolveShiftNote, unresolveShiftNote, deleteShiftNote } = useHostel();
  const { t } = useTranslation();
  const { currentStaff, activeStaffList } = useStaff();

  const [filter, setFilter] = useState<FilterType>("all");
  const [newNoteContent, setNewNoteContent] = useState("");
  const [newNoteCategory, setNewNoteCategory] = useState<ShiftNoteCategory>("general");
  const [newNotePriority, setNewNotePriority] = useState<"normal" | "urgent">("normal");
  const [newNoteAssignee, setNewNoteAssignee] = useState("");
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);

  const filteredNotes = useMemo(() => {
    const sorted = [...shiftNotes].sort(
      (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
    );
    switch (filter) {
      case "all":
        return sorted;
      case "unresolved":
        return sorted.filter((n) => !n.isResolved);
      case "urgent":
        return sorted.filter((n) => n.priority === "urgent" && !n.isResolved);
      case "manual":
        return sorted.filter((n) => !n.autoGenerated);
      case "auto":
        return sorted.filter((n) => n.autoGenerated);
      default:
        return sorted.filter((n) => n.category === filter);
    }
  }, [shiftNotes, filter]);

  const handleSubmit = () => {
    if (!newNoteContent.trim()) return;
    addShiftNote({
      content: newNoteContent.trim(),
      category: newNoteCategory,
      priority: newNotePriority,
      author: currentStaff?.name || "Unknown",
      assignee: newNoteAssignee.trim() || undefined,
      source: "manual",
      autoGenerated: false,
    });
    setNewNoteContent("");
    setNewNoteCategory("general");
    setNewNotePriority("normal");
    setNewNoteAssignee("");
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  const handleResolveToggle = (note: ShiftNote) => {
    if (note.isResolved) {
      unresolveShiftNote(note.id);
    } else {
      resolveShiftNote(note.id);
    }
  };

  const handleDelete = (noteId: string) => {
    if (deleteConfirmId === noteId) {
      deleteShiftNote(noteId);
      setDeleteConfirmId(null);
    } else {
      setDeleteConfirmId(noteId);
    }
  };

  const handleRelatedNavigate = (relatedType: string) => {
    if (!onNavigate) return;
    switch (relatedType) {
      case "guest":
        onNavigate("checkin");
        break;
      case "bed":
        onNavigate("bedboard");
        break;
    }
  };

  const relatedLinkI18nKeys: Record<string, { i18nKey: string; tab: string }> = {
    guest: { i18nKey: "shiftlog.viewGuest", tab: "checkin" },
    bed: { i18nKey: "shiftlog.viewBed", tab: "bedboard" },
  };

  const filterTabs: { key: FilterType; label: string }[] = [
    { key: "all", label: t("shiftlog.all") || "All" },
    { key: "unresolved", label: t("shiftlog.unresolved") || "Unresolved" },
    { key: "urgent", label: t("shiftlog.urgent") || "Urgent" },
    { key: "manual", label: t("shiftlog.manual") || "Manual" },
    { key: "auto", label: t("shiftlog.auto") || "Auto" },
    { key: "general", label: t("shiftlog.general") || "General" },
    { key: "late-arrival", label: t("shiftlog.lateArrival") || "Late Arrival" },
    { key: "maintenance", label: t("shiftlog.maintenance") || "Maintenance" },
    { key: "pickup", label: t("shiftlog.pickup") || "Pickup" },
    { key: "laundry", label: t("shiftlog.laundry") || "Laundry" },
  ];

  const unresolvedCount = shiftNotes.filter((n) => !n.isResolved).length;
  const urgentCount = shiftNotes.filter((n) => n.priority === "urgent" && !n.isResolved).length;

  return (
    <div className="max-w-3xl mx-auto space-y-6 pb-20 md:pb-0">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">
          {t("shiftlog.title") || "Shift Log"}
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          {unresolvedCount} {t("shiftlog.unresolved") || "unresolved"}
          {urgentCount > 0 && (
            <span className="text-red-500 font-medium">
              {" "}
              &middot; {urgentCount} {t("shiftlog.urgent") || "urgent"}
            </span>
          )}
        </p>
      </div>

      {/* Quick Add Bar */}
      <div className="bg-white rounded-xl border shadow-sm p-4 space-y-3">
        <div className="flex gap-2">
          <input
            type="text"
            value={newNoteContent}
            onChange={(e) => setNewNoteContent(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={t("shiftlog.addNote") || "Add a shift note..."}
            className="flex-1 px-3 py-2 text-sm border rounded-lg bg-zinc-50 border-zinc-200 focus:outline-none focus:ring-2 focus:ring-zinc-300 focus:border-transparent placeholder:text-muted-foreground"
          />
          <Button
            size="sm"
            className="h-9 gap-1.5 shrink-0"
            onClick={handleSubmit}
            disabled={!newNoteContent.trim()}
          >
            <Plus className="h-4 w-4" />
            {t("shiftlog.add") || "Add"}
          </Button>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <select
            value={newNoteCategory}
            onChange={(e) => setNewNoteCategory(e.target.value as ShiftNoteCategory)}
            className="text-xs px-2.5 py-1.5 rounded-lg border border-zinc-200 bg-zinc-50 text-zinc-700 focus:outline-none focus:ring-2 focus:ring-zinc-300"
          >
            {Object.entries(categoryI18nKeys).map(([key, i18nKey]) => (
              <option key={key} value={key}>
                {t(i18nKey) || key}
              </option>
            ))}
          </select>
          <button
            type="button"
            onClick={() => setNewNotePriority((p) => (p === "urgent" ? "normal" : "urgent"))}
            className={`inline-flex items-center gap-1 text-xs px-2.5 py-1.5 rounded-lg border transition-colors ${
              newNotePriority === "urgent"
                ? "border-red-300 bg-red-50 text-red-600"
                : "border-zinc-200 bg-zinc-50 text-muted-foreground hover:text-zinc-700"
            }`}
          >
            <AlertTriangle className="h-3 w-3" />
            {t("shiftlog.urgent") || "Urgent"}
          </button>
          <select
            value={newNoteAssignee}
            onChange={(e) => setNewNoteAssignee(e.target.value)}
            className="text-xs px-2.5 py-1.5 rounded-lg border border-zinc-200 bg-zinc-50 text-zinc-700 focus:outline-none focus:ring-2 focus:ring-zinc-300"
          >
            <option value="">{t("shiftlog.assignTo") || "Assign to..."}</option>
            {activeStaffList.map((s) => (
              <option key={s.id} value={s.name}>{s.name} ({t(`staff.${s.role}`) || s.role})</option>
            ))}
          </select>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex gap-1.5 overflow-x-auto pb-1 -mb-1 scrollbar-none">
        {filterTabs.map((tab) => {
          const isActive = filter === tab.key;
          return (
            <button
              key={tab.key}
              onClick={() => setFilter(tab.key)}
              className={`shrink-0 text-xs font-medium px-3 py-1.5 rounded-full transition-colors ${
                isActive
                  ? "bg-primary text-primary-foreground"
                  : "border border-border text-foreground hover:bg-muted"
              }`}
            >
              {tab.label}
            </button>
          );
        })}
      </div>

      {/* Notes Timeline */}
      <div className="space-y-3">
        {filteredNotes.length === 0 && (
          <div className="text-center py-12 text-muted-foreground">
            <ClipboardList className="h-10 w-10 mx-auto mb-3 opacity-50" />
            <p className="text-sm">{t("shiftlog.noNotes") || "No shift notes found."}</p>
          </div>
        )}
        {filteredNotes.map((note) => {
          const CategoryIcon = categoryIcons[note.category];
          const isDeleting = deleteConfirmId === note.id;
          const srcIcon = sourceIcons[note.source];
          const srcLabel = t(sourceI18nKeys[note.source]) || note.source;

          return (
            <div
              key={note.id}
              className={`bg-white rounded-xl border shadow-sm border-l-4 transition-opacity ${
                categoryBorderColors[note.category]
              } ${note.isResolved ? "opacity-50" : ""} ${
                note.priority === "urgent" && !note.isResolved
                  ? "!border-l-red-500 ring-1 ring-red-100"
                  : ""
              }`}
            >
              <div className="p-4">
                <div className="flex items-start gap-3">
                  {/* Category Icon */}
                  <div
                    className={`shrink-0 p-1.5 rounded-lg ${categoryColors[note.category]}`}
                  >
                    <CategoryIcon className="h-4 w-4" />
                  </div>

                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      <span className="text-xs font-medium text-foreground">
                        {note.author}
                      </span>
                      <span className="text-xs text-muted-foreground">
                        {formatDistanceToNow(parseISO(note.createdAt), {
                          addSuffix: true,
                        })}
                      </span>
                      {note.autoGenerated && srcIcon && (
                        <span className={`inline-flex items-center gap-1 text-xs font-medium px-1.5 py-0.5 rounded ${srcIcon.className}`}>
                          <srcIcon.icon className="h-3 w-3" />
                          {srcLabel}
                        </span>
                      )}
                      {note.priority === "urgent" && !note.isResolved && (
                        <AlertTriangle className="h-3.5 w-3.5 text-red-500 shrink-0" />
                      )}
                      {note.isResolved && (
                        <span className="inline-flex items-center gap-0.5 text-xs text-emerald-600 font-medium">
                          <Check className="h-3 w-3" />
                          {t("shiftlog.resolved") || "Resolved"}
                        </span>
                      )}
                    </div>
                    <p
                      className={`text-sm text-zinc-700 leading-relaxed ${
                        note.isResolved ? "line-through text-muted-foreground" : ""
                      }`}
                    >
                      {note.content}
                    </p>
                    <div className="flex items-center gap-3 mt-1.5 flex-wrap">
                      {note.assignee && (
                        <p className="text-xs text-muted-foreground">
                          {t("shiftlog.assignedTo") || "Assigned to"}:{" "}
                          <span className="text-zinc-600 font-medium">{note.assignee}</span>
                        </p>
                      )}
                      {note.relatedType && relatedLinkI18nKeys[note.relatedType] && onNavigate && (
                        <button
                          onClick={() => handleRelatedNavigate(note.relatedType!)}
                          className="text-xs text-blue-500 hover:text-blue-700 hover:underline font-medium"
                        >
                          {t(relatedLinkI18nKeys[note.relatedType].i18nKey) || note.relatedType}
                        </button>
                      )}
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="shrink-0 flex items-center gap-1">
                    <button
                      onClick={() => handleResolveToggle(note)}
                      className={`p-1.5 rounded-lg transition-colors ${
                        note.isResolved
                          ? "text-muted-foreground hover:text-zinc-600 hover:bg-zinc-100"
                          : "text-emerald-500 hover:bg-emerald-50"
                      }`}
                      title={
                        note.isResolved
                          ? t("shiftlog.unresolve") || "Unresolve"
                          : t("shiftlog.resolve") || "Resolve"
                      }
                    >
                      <Check className="h-4 w-4" />
                    </button>
                    {isDeleting ? (
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => handleDelete(note.id)}
                          className="p-1.5 rounded-lg text-red-500 hover:bg-red-50"
                          title={t("shiftlog.confirmDelete") || "Confirm delete"}
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                        <button
                          onClick={() => setDeleteConfirmId(null)}
                          className="p-1.5 rounded-lg text-muted-foreground hover:bg-zinc-100"
                          title={t("shiftlog.cancel") || "Cancel"}
                        >
                          <X className="h-4 w-4" />
                        </button>
                      </div>
                    ) : (
                      <button
                        onClick={() => setDeleteConfirmId(note.id)}
                        className="p-1.5 rounded-lg text-muted-foreground/70 hover:text-red-400 hover:bg-red-50 transition-colors"
                        title={t("shiftlog.delete") || "Delete"}
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    )}
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
