import { Room, Guest, ShiftNote, Task, Activity, Staff, GroupBooking, Referral, HostelPage, Promotion, GuestProfile } from './types';
import { addDays, format } from 'date-fns';

const today = new Date();
const t = (days: number) => format(addDays(today, days), 'yyyy-MM-dd');

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'r_101',
    number: '101',
    name: 'Mixed Dorm',
    type: 'dorm-mixed',
    pricePerNight: 85,
    bottomBunkPremium: 10,
    floor: 1,
    beds: [
      {
        id: 'b_101_1',
        roomId: 'r_101',
        name: 'A (Bottom)',
        bedType: 'bottom',
        status: 'occupied',
        guest: {
          id: 'g_1',
          name: 'Alex Johnson',
          country: 'Australia',
          countryCode: 'AU',
          gender: 'male',
          checkInDate: t(-2),
          checkOutDate: t(2),
          nights: 4,
          paymentStatus: 'paid',
          totalAmount: 340,
          paidAmount: 340,
          passportScanned: true,
          source: 'walk-in',
        }
      },
      {
        id: 'b_101_2',
        roomId: 'r_101',
        name: 'B (Top)',
        bedType: 'top',
        status: 'cleaning',
        reservations: [
          {
            id: 'g_res_1',
            name: 'John Doe',
            country: 'USA',
            countryCode: 'US',
            gender: 'male',
            checkInDate: t(2),
            checkOutDate: t(5),
            nights: 3,
            paymentStatus: 'paid',
            totalAmount: 255,
            paidAmount: 255,
            passportScanned: false,
            source: 'booking',
          }
        ]
      },
      {
        id: 'b_101_3',
        roomId: 'r_101',
        name: 'C (Bottom)',
        bedType: 'bottom',
        status: 'reserved',
        guest: {
          id: 'g_2',
          name: 'Maria Garcia',
          country: 'Spain',
          countryCode: 'ES',
          gender: 'female',
          checkInDate: t(0),
          checkOutDate: t(3),
          nights: 3,
          paymentStatus: 'unpaid',
          totalAmount: 255,
          passportScanned: false,
          source: 'booking',
        }
      },
      {
        id: 'b_101_4',
        roomId: 'r_101',
        name: 'D (Top)',
        bedType: 'top',
        status: 'empty',
        reservations: [
          {
            id: 'g_res_2',
            name: 'Anna Lee',
            country: 'South Korea',
            countryCode: 'KR',
            checkInDate: t(4),
            checkOutDate: t(9),
            nights: 5,
            paymentStatus: 'partial',
            totalAmount: 425,
            paidAmount: 200,
            passportScanned: false,
            source: 'expedia',
          }
        ]
      },
      {
        id: 'b_101_5',
        roomId: 'r_101',
        name: 'E (Bottom)',
        bedType: 'bottom',
        status: 'occupied',
        guest: {
          id: 'g_3',
          name: 'Yuki Tanaka',
          country: 'Japan',
          countryCode: 'JP',
          checkInDate: t(-1),
          checkOutDate: t(1),
          nights: 2,
          paymentStatus: 'paid',
          totalAmount: 170,
          paidAmount: 170,
          passportScanned: true,
          source: 'airbnb',
        }
      },
      {
        id: 'b_101_6',
        roomId: 'r_101',
        name: 'F (Top)',
        bedType: 'top',
        status: 'occupied',
        guest: {
          id: 'g_4',
          name: 'Emma Smith',
          country: 'UK',
          countryCode: 'GB',
          gender: 'female',
          checkInDate: t(0),
          checkOutDate: t(4),
          nights: 4,
          paymentStatus: 'unpaid',
          totalAmount: 340,
          passportScanned: false,
          source: 'walk-in',
        }
      },
      {
        id: 'b_101_7',
        roomId: 'r_101',
        name: 'G (Bottom)',
        bedType: 'bottom',
        status: 'empty',
      },
      {
        id: 'b_101_8',
        roomId: 'r_101',
        name: 'H (Top)',
        bedType: 'top',
        status: 'empty',
      },
    ]
  },
  {
    id: 'r_102',
    number: '102',
    name: 'Female Dorm',
    type: 'dorm-female',
    pricePerNight: 95,
    bottomBunkPremium: 10,
    floor: 1,
    beds: [
      {
        id: 'b_102_1',
        roomId: 'r_102',
        name: 'A (Bottom)',
        bedType: 'bottom',
        status: 'late-arrival',
        guest: {
          id: 'g_5',
          name: 'Sophie Martin',
          country: 'France',
          countryCode: 'FR',
          checkInDate: t(0),
          checkOutDate: t(2),
          nights: 2,
          paymentStatus: 'partial',
          totalAmount: 170,
          paidAmount: 85,
          passportScanned: false,
          notes: 'Arriving at 1AM. Flight delayed.',
          source: 'booking',
        }
      },
      { id: 'b_102_2', roomId: 'r_102', name: 'B (Top)', bedType: 'top', status: 'empty', reservations: [
        {
          id: 'g_res_3',
          name: 'Sarah Connor',
          country: 'USA',
          countryCode: 'US',
          checkInDate: t(1),
          checkOutDate: t(3),
          nights: 2,
          paymentStatus: 'paid',
          totalAmount: 170,
          paidAmount: 170,
          passportScanned: true,
          source: 'booking',
        }
      ] },
      { id: 'b_102_3', roomId: 'r_102', name: 'C (Bottom)', bedType: 'bottom', status: 'empty' },
      { id: 'b_102_4', roomId: 'r_102', name: 'D (Top)', bedType: 'top', status: 'cleaning' },
      {
        id: 'b_102_5',
        roomId: 'r_102',
        name: 'E (Bottom)',
        bedType: 'bottom',
        status: 'occupied',
        guest: {
          id: 'g_6',
          name: 'Clara Weber',
          country: 'Germany',
          countryCode: 'DE',
          checkInDate: t(-3),
          checkOutDate: t(0),
          nights: 3,
          paymentStatus: 'paid',
          totalAmount: 255,
          paidAmount: 255,
          passportScanned: true,
          source: 'expedia',
        }
      },
      { id: 'b_102_6', roomId: 'r_102', name: 'F (Top)', bedType: 'top', status: 'cleaning' },
    ]
  },
  {
    id: 'r_201',
    number: '201',
    name: 'Private Room',
    type: 'private',
    pricePerNight: 150,
    floor: 2,
    beds: [
      {
        id: 'b_201_1',
        roomId: 'r_201',
        name: 'Double Bed',
        bedType: 'double',
        status: 'occupied',
        guest: {
          id: 'g_7',
          name: 'David & Lisa',
          country: 'Canada',
          countryCode: 'CA',
          checkInDate: t(-1),
          checkOutDate: t(1),
          nights: 2,
          paymentStatus: 'paid',
          totalAmount: 300,
          paidAmount: 300,
          passportScanned: true,
          source: 'booking',
        }
      }
    ]
  }
];

export const ARRIVALS: Guest[] = [
  {
    id: 'g_arr_1',
    name: 'Lucas Silva',
    country: 'Brazil',
    countryCode: 'BR',
    gender: 'male',
    checkInDate: t(0),
    checkOutDate: t(5),
    nights: 5,
    paymentStatus: 'unpaid',
    totalAmount: 425,
    passportScanned: false,
    notes: 'Requested bottom bed if possible.',
    source: 'walk-in',
    roomPreference: 'Bottom bunk',
  },
  {
    id: 'g_arr_2',
    name: 'Nina Jensen',
    country: 'Denmark',
    countryCode: 'DK',
    gender: 'female',
    checkInDate: t(0),
    checkOutDate: t(2),
    nights: 2,
    paymentStatus: 'paid',
    totalAmount: 170,
    paidAmount: 170,
    passportScanned: false,
    source: 'booking',
  }
];

export const INITIAL_STAFF: Staff[] = [
  { id: "staff_1", name: "Emma", role: "manager", pin: "1234", isActive: true, createdAt: "2024-01-01T00:00:00Z" },
  { id: "staff_2", name: "Maria", role: "reception", pin: "1234", isActive: true, createdAt: "2024-01-15T00:00:00Z" },
  { id: "staff_3", name: "Jake", role: "cleaning", pin: "1234", isActive: true, createdAt: "2024-02-01T00:00:00Z" },
  { id: "staff_4", name: "Tony", role: "reception", pin: "1234", isActive: true, createdAt: "2024-03-01T00:00:00Z" },
];

const now = new Date().toISOString();

export const INITIAL_SHIFT_NOTES: ShiftNote[] = [
  {
    id: 'sn_1',
    content: 'Guest Sophie Martin arriving at 1AM — flight delayed. Leave key at reception.',
    category: 'late-arrival',
    priority: 'urgent',
    author: 'Emma',
    createdAt: new Date(today.getTime() - 2 * 3600000).toISOString(),
    isResolved: false,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_2',
    content: 'Laundry machine #2 broken again. Technician called, ETA tomorrow.',
    category: 'laundry',
    priority: 'urgent',
    author: 'Maria',
    assignee: 'Jake',
    createdAt: new Date(today.getTime() - 4 * 3600000).toISOString(),
    isResolved: false,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_3',
    content: 'Room 102 Bed D — guest checked out, needs deep clean (spill on mattress).',
    category: 'general',
    priority: 'normal',
    author: 'Emma',
    assignee: 'Maria',
    createdAt: new Date(today.getTime() - 5 * 3600000).toISOString(),
    isResolved: false,
    source: 'checkout',
    relatedId: 'b_102_4',
    relatedType: 'bed',
    autoGenerated: true,
  },
  {
    id: 'sn_4',
    content: 'Airport pickup for Lucas Silva — flight lands 18:30 at Terminal 2.',
    category: 'pickup',
    priority: 'normal',
    author: 'Jake',
    assignee: 'Tony',
    createdAt: new Date(today.getTime() - 6 * 3600000).toISOString(),
    isResolved: false,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_5',
    content: 'AC in Room 201 making noise again. Guest complained at midnight.',
    category: 'maintenance',
    priority: 'normal',
    author: 'Tony',
    assignee: 'Jake',
    createdAt: new Date(today.getTime() - 8 * 3600000).toISOString(),
    isResolved: false,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_6',
    content: 'Emma checked out from Bed A3. Left a positive review on HW.',
    category: 'general',
    priority: 'normal',
    author: 'System',
    createdAt: new Date(today.getTime() - 10 * 3600000).toISOString(),
    resolvedAt: new Date(today.getTime() - 9 * 3600000).toISOString(),
    isResolved: true,
    source: 'checkout',
    relatedType: 'guest',
    autoGenerated: true,
  },
  {
    id: 'sn_7',
    content: 'Restock toilet paper in Female Dorm bathroom.',
    category: 'other',
    priority: 'normal',
    author: 'Maria',
    assignee: 'Tony',
    createdAt: new Date(today.getTime() - 12 * 3600000).toISOString(),
    resolvedAt: new Date(today.getTime() - 11 * 3600000).toISOString(),
    isResolved: true,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_8',
    content: 'New guest Nina Jensen — requested bottom bunk if available.',
    category: 'general',
    priority: 'normal',
    author: 'Jake',
    createdAt: new Date(today.getTime() - 1 * 3600000).toISOString(),
    isResolved: false,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_9',
    content: 'Alex Johnson checked in to Bed 101-A.',
    category: 'general',
    priority: 'normal',
    author: 'System',
    createdAt: new Date(today.getTime() - 48 * 3600000).toISOString(),
    isResolved: true,
    resolvedAt: new Date(today.getTime() - 48 * 3600000).toISOString(),
    source: 'checkin',
    relatedId: 'g_1',
    relatedType: 'guest',
    autoGenerated: true,
  },
  {
    id: 'sn_10',
    content: 'Bed 101-B marked as clean and ready.',
    category: 'general',
    priority: 'normal',
    author: 'System',
    createdAt: new Date(today.getTime() - 6 * 3600000).toISOString(),
    isResolved: true,
    resolvedAt: new Date(today.getTime() - 6 * 3600000).toISOString(),
    source: 'cleaning',
    relatedId: 'b_101_2',
    relatedType: 'bed',
    autoGenerated: true,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_1',
    title: 'Replace light bulb in Room 101',
    description: 'Bed F top bunk light is out. Replacement bulb in storage closet.',
    status: 'open',
    priority: 'medium',
    assignee: 'Jake',
    category: 'maintenance',
    createdAt: new Date(today.getTime() - 24 * 3600000).toISOString(),
    comments: [],
  },
  {
    id: 'task_2',
    title: 'Airport pickup — Lucas Silva',
    description: 'Flight lands 18:30 Terminal 2. White van.',
    status: 'open',
    priority: 'high',
    assignee: 'Tony',
    dueDate: t(0),
    category: 'pickup',
    createdAt: new Date(today.getTime() - 6 * 3600000).toISOString(),
    comments: [],
  },
  {
    id: 'task_3',
    title: 'Extra pillow for Room 201',
    description: 'Guest Lisa requested an extra pillow.',
    status: 'in-progress',
    priority: 'low',
    assignee: 'Maria',
    category: 'guest-request',
    createdAt: new Date(today.getTime() - 3 * 3600000).toISOString(),
    comments: [
      {
        id: 'tc_1',
        author: 'Maria',
        content: 'No clean pillows available, washing now.',
        createdAt: new Date(today.getTime() - 2 * 3600000).toISOString(),
      }
    ],
  },
  {
    id: 'task_4',
    title: 'Fix locker #7 in Mixed Dorm',
    description: 'Lock is jammed. Guest cannot secure belongings.',
    status: 'open',
    priority: 'high',
    assignee: 'Jake',
    category: 'maintenance',
    createdAt: new Date(today.getTime() - 48 * 3600000).toISOString(),
    comments: [],
  },
  {
    id: 'task_5',
    title: 'Restock towels',
    description: 'Running low on clean towels. Need 20 by evening.',
    status: 'in-progress',
    priority: 'medium',
    assignee: 'Maria',
    category: 'restock',
    createdAt: new Date(today.getTime() - 5 * 3600000).toISOString(),
    comments: [],
  },
  {
    id: 'task_6',
    title: 'Check fire extinguisher expiry',
    description: 'Annual check due this month.',
    status: 'open',
    priority: 'low',
    category: 'maintenance',
    createdAt: new Date(today.getTime() - 72 * 3600000).toISOString(),
    comments: [],
  },
  {
    id: 'task_7',
    title: 'Welcome drink for Nina Jensen',
    status: 'completed',
    priority: 'low',
    assignee: 'Emma',
    category: 'guest-request',
    createdAt: new Date(today.getTime() - 8 * 3600000).toISOString(),
    completedAt: new Date(today.getTime() - 7 * 3600000).toISOString(),
    comments: [],
  },
  {
    id: 'task_8',
    title: 'Print new city maps',
    description: 'Old maps are outdated. New edition available at tourist office.',
    status: 'open',
    priority: 'low',
    category: 'restock',
    createdAt: new Date(today.getTime() - 24 * 3600000).toISOString(),
    comments: [],
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act_1',
    name: 'Pub Crawl',
    date: t(0),
    time: '19:00',
    capacity: 15,
    price: 10,
    location: 'Meet at reception',
    notes: 'Bring ID. 3 bars + 1 club included.',
    status: 'upcoming',
    participants: [
      { id: 'ap_1', guestName: 'Alex Johnson', bedName: '101-A', checkedIn: false },
      { id: 'ap_2', guestName: 'Yuki Tanaka', bedName: '101-E', checkedIn: false },
      { id: 'ap_3', guestName: 'Emma Smith', bedName: '101-F', checkedIn: false },
      { id: 'ap_4', guestName: 'Lucas Silva', checkedIn: false },
      { id: 'ap_5', guestName: 'David & Lisa', bedName: '201', checkedIn: false },
      { id: 'ap_6', guestName: 'Clara Weber', bedName: '102-E', checkedIn: false },
      { id: 'ap_7', guestName: 'Nina Jensen', checkedIn: false },
      { id: 'ap_8', guestName: 'Walk-in guest (Mike)', checkedIn: false },
    ],
  },
  {
    id: 'act_2',
    name: 'Yoga Class',
    date: t(0),
    time: '08:00',
    capacity: 10,
    price: 5,
    location: 'Rooftop',
    status: 'upcoming',
    participants: [
      { id: 'ap_9', guestName: 'Sophie Martin', bedName: '102-A', checkedIn: false },
      { id: 'ap_10', guestName: 'Nina Jensen', checkedIn: false },
      { id: 'ap_11', guestName: 'Emma Smith', bedName: '101-F', checkedIn: false },
      { id: 'ap_12', guestName: 'Clara Weber', bedName: '102-E', checkedIn: false },
    ],
  },
  {
    id: 'act_3',
    name: 'Walking Tour',
    date: t(1),
    time: '10:00',
    capacity: 12,
    price: 0,
    location: 'Main entrance',
    notes: 'Free tour, tips appreciated.',
    status: 'upcoming',
    participants: [
      { id: 'ap_13', guestName: 'Alex Johnson', bedName: '101-A', checkedIn: false },
      { id: 'ap_14', guestName: 'John Doe', checkedIn: false },
    ],
  },
  {
    id: 'act_4',
    name: 'BBQ Night',
    date: t(2),
    time: '18:00',
    capacity: 20,
    price: 8,
    location: 'Garden',
    status: 'upcoming',
    participants: [],
  },
];

export const INITIAL_GROUP_BOOKINGS: GroupBooking[] = [
  {
    id: 'gb_1',
    leaderName: "Marco's Surf Crew",
    source: 'direct',
    checkInDate: t(0),
    checkOutDate: t(3),
    memberIds: ['g_1', 'g_gb_1', 'g_gb_2', 'g_gb_3'],
    bedIds: ['b_101_7', 'b_101_8', 'b_102_3', 'b_102_4'],
    paymentMode: 'shared',
    totalAmount: 680,
    paidAmount: 340,
    notes: 'Surf crew — need board storage space.',
    createdAt: new Date(today.getTime() - 72 * 3600000).toISOString(),
  },
  {
    id: 'gb_2',
    leaderName: 'School Trip - Berlin',
    source: 'group',
    checkInDate: t(5),
    checkOutDate: t(8),
    memberIds: ['g_gb_4', 'g_gb_5', 'g_gb_6', 'g_gb_7', 'g_gb_8', 'g_gb_9'],
    bedIds: [],
    paymentMode: 'split',
    totalAmount: 1530,
    paidAmount: 0,
    notes: 'School group of 6 students. Need adjoining beds if possible.',
    createdAt: new Date(today.getTime() - 48 * 3600000).toISOString(),
  },
];

export const INITIAL_REFERRALS: Referral[] = [
  {
    id: 'ref_1',
    code: 'BUNKDESK-ALEX-3K7',
    referrerGuestId: 'g_1',
    referrerGuestName: 'Alex Johnson',
    usedByGuestIds: ['g_arr_1', 'g_gb_1'],
    reward: '10% off',
    commissionSaved: 68,
    createdAt: new Date(today.getTime() - 30 * 24 * 3600000).toISOString(),
  },
  {
    id: 'ref_2',
    code: 'BUNKDESK-SOPHIE-9M2',
    referrerGuestId: 'g_5',
    referrerGuestName: 'Sophie Martin',
    usedByGuestIds: ['g_arr_2'],
    reward: 'Free breakfast',
    commissionSaved: 25,
    createdAt: new Date(today.getTime() - 14 * 24 * 3600000).toISOString(),
  },
];

export const INITIAL_HOSTEL_PAGE: HostelPage = {
  id: 'hp_1',
  template: 'beach',
  hostelName: 'Sunset Backpackers',
  slug: 'sunset-backpackers',
  description: 'A chill beachside hostel with sunset views, surfboard rentals, and the best vibes in town.',
  coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=tropical%20beach%20hostel%20sunset%20palm%20trees%20backpackers&image_size=landscape_16_9',
  photos: [
    'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=surf%20hostel%20interior%20bunk%20beds%20bohemian%20decor&image_size=landscape_16_9',
    'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=dorm%20room%20beach%20vibe%20sunlight%20wooden%20bunks&image_size=landscape_16_9',
    'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=hostel%20common%20area%20hammocks%20tropical%20lounge&image_size=landscape_16_9',
  ],
  facilities: ['WiFi', 'Kitchen', 'Surfboard Rental', 'Locker', 'Laundry', 'Bar'],
  contactEmail: 'hello@sunsetbackpackers.com',
  contactPhone: '+1-555-0199',
  address: '123 Beach Road, Sunset Bay',
  published: true,
  updatedAt: new Date(today.getTime() - 7 * 24 * 3600000).toISOString(),
};

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 'promo_1',
    type: 'last-minute',
    name: 'Last Minute Deal!',
    discount: 20,
    startDate: t(0),
    endDate: t(3),
    active: true,
    createdAt: new Date(today.getTime() - 24 * 3600000).toISOString(),
  },
  {
    id: 'promo_2',
    type: 'long-stay',
    name: 'Stay 7+ Nights',
    discount: 15,
    startDate: t(7),
    endDate: t(30),
    minNights: 7,
    active: true,
    createdAt: new Date(today.getTime() - 48 * 3600000).toISOString(),
  },
];

export const INITIAL_GUEST_PROFILES: GuestProfile[] = [
  {
    id: 'gp_1',
    name: 'Marco Rossi',
    email: 'marco@gmail.com',
    whatsapp: '+39 333 1234567',
    country: 'Italy',
    countryCode: 'IT',
    gender: 'male',
    tags: ['digital-nomad', 'repeat-guest'],
    totalStays: 4,
    totalNights: 42,
    totalSpent: 3360,
    firstStayDate: '2025-03-15',
    lastStayDate: '2025-11-20',
  },
  {
    id: 'gp_2',
    name: 'Yuki Tanaka',
    email: 'yuki.tanaka@yahoo.co.jp',
    country: 'Japan',
    countryCode: 'JP',
    gender: 'female',
    tags: ['backpacker', 'repeat-guest'],
    totalStays: 2,
    totalNights: 10,
    totalSpent: 850,
    firstStayDate: '2025-06-01',
    lastStayDate: '2025-09-10',
  },
  {
    id: 'gp_3',
    name: 'Lena Müller',
    email: 'lena.m@web.de',
    whatsapp: '+49 170 9876543',
    country: 'Germany',
    countryCode: 'DE',
    gender: 'female',
    tags: ['long-stay', 'vip'],
    totalStays: 1,
    totalNights: 30,
    totalSpent: 2550,
    firstStayDate: '2025-08-01',
    lastStayDate: '2025-08-31',
  },
];
