import { Room, Guest, ShiftNote, Staff, GroupBooking, Referral, HostelPage, Promotion, GuestProfile } from './types';
import { addDays, format } from 'date-fns';

const today = new Date();
const t = (days: number) => format(addDays(today, days), 'yyyy-MM-dd');

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'r_101',
    number: '101',
    name: 'Mixed Dorm',
    type: 'dorm-mixed',
    pricePerNight: 85,
    bottomBunkPremium: 10,
    floor: 1,
    beds: [
      {
        id: 'b_101_1',
        roomId: 'r_101',
        name: 'A (Bottom)',
        bedType: 'bottom',
        status: 'occupied',
        guest: {
          id: 'g_1',
          name: 'Alex Johnson',
          firstName: 'Alex',
          lastName: 'Johnson',
          country: 'Australia',
          countryCode: 'AU',
          gender: 'male',
          checkInDate: t(-2),
          checkOutDate: t(2),
          nights: 4,
          paymentStatus: 'paid',
          totalAmount: 340,
          paidAmount: 340,
          passportScanned: true,
          source: 'walk-in',
          email: 'alex.johnson@email.com',
          phone: '+61-412-345-678',
          idType: 'passport',
          arrivalTime: 'afternoon',
          bookingSource: 'walk-in',
          referral: '',
        }
      },
      {
        id: 'b_101_2',
        roomId: 'r_101',
        name: 'B (Top)',
        bedType: 'top',
        status: 'cleaning',
        reservations: [
          {
            id: 'g_res_1',
            name: 'John Doe',
            firstName: 'John',
            lastName: 'Doe',
            country: 'USA',
            countryCode: 'US',
            gender: 'male',
            checkInDate: t(2),
            checkOutDate: t(5),
            nights: 3,
            paymentStatus: 'paid',
            totalAmount: 255,
            paidAmount: 255,
            passportScanned: false,
            source: 'booking',
            email: 'john.doe@email.com',
            phone: '+1-555-123-4567',
            idType: 'passport',
            arrivalTime: 'afternoon',
            bookingSource: 'email',
            referral: '',
          }
        ]
      },
      {
        id: 'b_101_3',
        roomId: 'r_101',
        name: 'C (Bottom)',
        bedType: 'bottom',
        status: 'reserved',
        guest: {
          id: 'g_2',
          name: 'Maria Garcia',
          firstName: 'Maria',
          lastName: 'Garcia',
          country: 'Spain',
          countryCode: 'ES',
          gender: 'female',
          checkInDate: t(0),
          checkOutDate: t(3),
          nights: 3,
          paymentStatus: 'unpaid',
          totalAmount: 255,
          passportScanned: false,
          source: 'booking',
          email: 'maria.garcia@email.com',
          phone: '+34-612-345-678',
          idType: 'passport',
          arrivalTime: 'morning',
          bookingSource: 'email',
          referral: '',
        }
      },
      {
        id: 'b_101_4',
        roomId: 'r_101',
        name: 'D (Top)',
        bedType: 'top',
        status: 'empty',
        reservations: [
          {
            id: 'g_res_2',
            name: 'Anna Lee',
            firstName: 'Anna',
            lastName: 'Lee',
            country: 'South Korea',
            countryCode: 'KR',
            gender: 'female',
            checkInDate: t(4),
            checkOutDate: t(9),
            nights: 5,
            paymentStatus: 'partial',
            totalAmount: 425,
            paidAmount: 200,
            passportScanned: false,
            source: 'expedia',
            email: 'anna.lee@email.com',
            phone: '+82-10-1234-5678',
            idType: 'passport',
            arrivalTime: 'evening',
            bookingSource: 'email',
            referral: '',
          }
        ]
      },
      {
        id: 'b_101_5',
        roomId: 'r_101',
        name: 'E (Bottom)',
        bedType: 'bottom',
        status: 'occupied',
        guest: {
          id: 'g_3',
          name: 'Yuki Tanaka',
          firstName: 'Yuki',
          lastName: 'Tanaka',
          country: 'Japan',
          countryCode: 'JP',
          gender: 'female',
          checkInDate: t(-1),
          checkOutDate: t(1),
          nights: 2,
          paymentStatus: 'paid',
          totalAmount: 170,
          paidAmount: 170,
          passportScanned: true,
          source: 'airbnb',
          email: 'yuki.tanaka@email.com',
          phone: '+81-90-1234-5678',
          idType: 'passport',
          arrivalTime: 'evening',
          bookingSource: 'email',
          referral: '',
        }
      },
      {
        id: 'b_101_6',
        roomId: 'r_101',
        name: 'F (Top)',
        bedType: 'top',
        status: 'occupied',
        guest: {
          id: 'g_4',
          name: 'Emma Smith',
          firstName: 'Emma',
          lastName: 'Smith',
          country: 'UK',
          countryCode: 'GB',
          gender: 'female',
          checkInDate: t(0),
          checkOutDate: t(4),
          nights: 4,
          paymentStatus: 'unpaid',
          totalAmount: 340,
          passportScanned: false,
          source: 'walk-in',
          email: 'emma.smith@email.com',
          phone: '+44-7911-123456',
          idType: 'passport',
          arrivalTime: 'afternoon',
          bookingSource: 'walk-in',
          referral: '',
        }
      },
      {
        id: 'b_101_7',
        roomId: 'r_101',
        name: 'G (Bottom)',
        bedType: 'bottom',
        status: 'empty',
      },
      {
        id: 'b_101_8',
        roomId: 'r_101',
        name: 'H (Top)',
        bedType: 'top',
        status: 'empty',
      },
    ]
  },
  {
    id: 'r_102',
    number: '102',
    name: 'Female Dorm',
    type: 'dorm-female',
    pricePerNight: 95,
    bottomBunkPremium: 10,
    floor: 1,
    beds: [
      {
        id: 'b_102_1',
        roomId: 'r_102',
        name: 'A (Bottom)',
        bedType: 'bottom',
        status: 'late-arrival',
        guest: {
          id: 'g_5',
          name: 'Sophie Martin',
          firstName: 'Sophie',
          lastName: 'Martin',
          country: 'France',
          countryCode: 'FR',
          gender: 'female',
          checkInDate: t(0),
          checkOutDate: t(2),
          nights: 2,
          paymentStatus: 'partial',
          totalAmount: 170,
          paidAmount: 85,
          passportScanned: false,
          notes: 'Arriving at 1AM. Flight delayed.',
          source: 'booking',
          email: 'sophie.martin@email.com',
          phone: '+33-6-12-34-56-78',
          idType: 'passport',
          arrivalTime: 'late',
          bookingSource: 'email',
          referral: '',
        }
      },
      { id: 'b_102_2', roomId: 'r_102', name: 'B (Top)', bedType: 'top', status: 'empty', reservations: [
        {
          id: 'g_res_3',
          name: 'Sarah Connor',
          firstName: 'Sarah',
          lastName: 'Connor',
          country: 'USA',
          countryCode: 'US',
          gender: 'female',
          checkInDate: t(1),
          checkOutDate: t(3),
          nights: 2,
          paymentStatus: 'paid',
          totalAmount: 170,
          paidAmount: 170,
          passportScanned: true,
          source: 'booking',
          email: 'sarah.connor@email.com',
          phone: '+1-555-987-6543',
          idType: 'passport',
          arrivalTime: 'morning',
          bookingSource: 'email',
          referral: '',
        }
      ] },
      { id: 'b_102_3', roomId: 'r_102', name: 'C (Bottom)', bedType: 'bottom', status: 'empty' },
      { id: 'b_102_4', roomId: 'r_102', name: 'D (Top)', bedType: 'top', status: 'cleaning' },
      {
        id: 'b_102_5',
        roomId: 'r_102',
        name: 'E (Bottom)',
        bedType: 'bottom',
        status: 'occupied',
        guest: {
          id: 'g_6',
          name: 'Clara Weber',
          firstName: 'Clara',
          lastName: 'Weber',
          country: 'Germany',
          countryCode: 'DE',
          gender: 'female',
          checkInDate: t(-3),
          checkOutDate: t(0),
          nights: 3,
          paymentStatus: 'paid',
          totalAmount: 255,
          paidAmount: 255,
          passportScanned: true,
          source: 'expedia',
          email: 'clara.weber@email.com',
          phone: '+49-170-1234567',
          idType: 'idCard',
          arrivalTime: 'morning',
          bookingSource: 'email',
          referral: '',
        }
      },
      { id: 'b_102_6', roomId: 'r_102', name: 'F (Top)', bedType: 'top', status: 'cleaning' },
    ]
  },
  {
    id: 'r_201',
    number: '201',
    name: 'Private Room',
    type: 'private',
    pricePerNight: 150,
    floor: 2,
    beds: [
      {
        id: 'b_201_1',
        roomId: 'r_201',
        name: 'Double Bed',
        bedType: 'double',
        status: 'occupied',
        guest: {
          id: 'g_7',
          name: 'David & Lisa',
          firstName: 'David',
          lastName: 'Miller',
          country: 'Canada',
          countryCode: 'CA',
          gender: 'other',
          checkInDate: t(-1),
          checkOutDate: t(1),
          nights: 2,
          paymentStatus: 'paid',
          totalAmount: 300,
          paidAmount: 300,
          passportScanned: true,
          source: 'booking',
          email: 'david.lisa@email.com',
          phone: '+1-416-555-0123',
          idType: 'passport',
          arrivalTime: 'afternoon',
          bookingSource: 'email',
          referral: '',
        }
      }
    ]
  }
];

export const ARRIVALS: Guest[] = [
  {
    id: 'g_arr_1',
    name: 'Lucas Silva',
    firstName: 'Lucas',
    lastName: 'Silva',
    country: 'Brazil',
    countryCode: 'BR',
    gender: 'male',
    checkInDate: t(0),
    checkOutDate: t(5),
    nights: 5,
    paymentStatus: 'unpaid',
    totalAmount: 425,
    phone: '+55-11-99876-5432',
    email: 'lucas.silva@mail.com',
    passportScanned: false,
    passportOrId: 'BR1234567',
    idType: 'passport',
    arrivalTime: 'afternoon',
    referral: 'Hostelworld',
    bookingSource: 'walk-in',
    notes: 'Requested bottom bed if possible.',
    source: 'walk-in',
    roomPreference: 'Bottom bunk',
  },
  {
    id: 'g_arr_2',
    name: 'Nina Jensen',
    firstName: 'Nina',
    lastName: 'Jensen',
    country: 'Denmark',
    countryCode: 'DK',
    gender: 'female',
    checkInDate: t(0),
    checkOutDate: t(2),
    nights: 2,
    paymentStatus: 'paid',
    totalAmount: 170,
    paidAmount: 170,
    phone: '+45-31-22-11-00',
    email: 'nina.jensen@mail.dk',
    passportScanned: false,
    passportOrId: 'DK9876543',
    idType: 'passport',
    arrivalTime: 'morning',
    referral: '',
    bookingSource: 'email',
    source: 'booking',
  },
  {
    id: 'g_arr_3',
    name: 'Sophie Müller',
    firstName: 'Sophie',
    lastName: 'Müller',
    country: 'Germany',
    countryCode: 'DE',
    gender: 'female',
    checkInDate: t(1),
    checkOutDate: t(4),
    nights: 3,
    paymentStatus: 'unpaid',
    totalAmount: 255,
    phone: '+49-30-12345678',
    email: 'sophie.mueller@mail.de',
    passportScanned: true,
    passportOrId: 'DE20150101234',
    idType: 'idCard',
    arrivalTime: 'late',
    referral: 'Google',
    bookingSource: 'walk-in',
    notes: 'Late check-in — leave key at reception.',
    source: 'walk-in',
  },
  {
    id: 'g_arr_4',
    name: 'Marco Rossi',
    firstName: 'Marco',
    lastName: 'Rossi',
    country: 'Italy',
    countryCode: 'IT',
    gender: 'male',
    checkInDate: t(0),
    checkOutDate: t(6),
    nights: 6,
    paymentStatus: 'paid',
    totalAmount: 510,
    paidAmount: 510,
    phone: '+39-06-1234-5678',
    email: 'marco.rossi@mail.it',
    passportScanned: true,
    passportOrId: 'IT-DL-20250101-7890',
    idType: 'driverLicense',
    arrivalTime: 'morning',
    referral: 'Booking.com',
    bookingSource: 'phone',
    source: 'booking',
  },
  {
    id: 'g_arr_5',
    name: 'Yuki Tanaka',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    country: 'Japan',
    countryCode: 'JP',
    gender: 'female',
    checkInDate: t(0),
    checkOutDate: t(3),
    nights: 3,
    paymentStatus: 'unpaid',
    totalAmount: 255,
    phone: '+81-3-1234-5678',
    email: 'yuki.tanaka@mail.jp',
    passportScanned: false,
    passportOrId: 'JPTR9988',
    idType: 'passport',
    arrivalTime: 'evening',
    referral: 'Instagram',
    bookingSource: 'walk-in',
    source: 'walk-in',
  },
  {
    id: 'g_arr_6',
    name: 'Wei Chen',
    firstName: 'Wei',
    lastName: 'Chen',
    country: 'China',
    countryCode: 'CN',
    gender: 'male',
    checkInDate: t(0),
    checkOutDate: t(2),
    nights: 2,
    paymentStatus: 'paid',
    totalAmount: 170,
    paidAmount: 170,
    phone: '+86-138-0013-8000',
    email: 'wei.chen@mail.cn',
    passportScanned: true,
    passportOrId: 'CN20250101X',
    idType: 'passport',
    arrivalTime: 'afternoon',
    referral: 'Friend',
    bookingSource: 'referral',
    source: 'referral',
  },
];

export const INITIAL_STAFF: Staff[] = [
  { id: "staff_1", name: "Emma", role: "manager", pin: "1234", isActive: true, createdAt: "2024-01-01T00:00:00Z" },
  { id: "staff_2", name: "Maria", role: "reception", pin: "1234", isActive: true, createdAt: "2024-01-15T00:00:00Z" },
  { id: "staff_3", name: "Jake", role: "cleaning", pin: "1234", isActive: true, createdAt: "2024-02-01T00:00:00Z" },
  { id: "staff_4", name: "Tony", role: "reception", pin: "1234", isActive: true, createdAt: "2024-03-01T00:00:00Z" },
];

const now = new Date().toISOString();

export const INITIAL_SHIFT_NOTES: ShiftNote[] = [
  {
    id: 'sn_1',
    content: 'Guest Sophie Martin arriving at 1AM — flight delayed. Leave key at reception.',
    category: 'late-arrival',
    priority: 'urgent',
    author: 'Emma',
    createdAt: new Date(today.getTime() - 2 * 3600000).toISOString(),
    isResolved: false,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_2',
    content: 'Laundry machine #2 broken again. Technician called, ETA tomorrow.',
    category: 'laundry',
    priority: 'urgent',
    author: 'Maria',
    assignee: 'Jake',
    createdAt: new Date(today.getTime() - 4 * 3600000).toISOString(),
    isResolved: false,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_3',
    content: 'Room 102 Bed D — guest checked out, needs deep clean (spill on mattress).',
    category: 'general',
    priority: 'normal',
    author: 'Emma',
    assignee: 'Maria',
    createdAt: new Date(today.getTime() - 5 * 3600000).toISOString(),
    isResolved: false,
    source: 'checkout',
    relatedId: 'b_102_4',
    relatedType: 'bed',
    autoGenerated: true,
  },
  {
    id: 'sn_4',
    content: 'Airport pickup for Lucas Silva — flight lands 18:30 at Terminal 2.',
    category: 'pickup',
    priority: 'normal',
    author: 'Jake',
    assignee: 'Tony',
    createdAt: new Date(today.getTime() - 6 * 3600000).toISOString(),
    isResolved: false,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_5',
    content: 'AC in Room 201 making noise again. Guest complained at midnight.',
    category: 'maintenance',
    priority: 'normal',
    author: 'Tony',
    assignee: 'Jake',
    createdAt: new Date(today.getTime() - 8 * 3600000).toISOString(),
    isResolved: false,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_6',
    content: 'Emma checked out from Bed A3. Left a positive review on HW.',
    category: 'general',
    priority: 'normal',
    author: 'System',
    createdAt: new Date(today.getTime() - 10 * 3600000).toISOString(),
    resolvedAt: new Date(today.getTime() - 9 * 3600000).toISOString(),
    isResolved: true,
    source: 'checkout',
    relatedType: 'guest',
    autoGenerated: true,
  },
  {
    id: 'sn_7',
    content: 'Restock toilet paper in Female Dorm bathroom.',
    category: 'other',
    priority: 'normal',
    author: 'Maria',
    assignee: 'Tony',
    createdAt: new Date(today.getTime() - 12 * 3600000).toISOString(),
    resolvedAt: new Date(today.getTime() - 11 * 3600000).toISOString(),
    isResolved: true,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_8',
    content: 'New guest Nina Jensen — requested bottom bunk if available.',
    category: 'general',
    priority: 'normal',
    author: 'Jake',
    createdAt: new Date(today.getTime() - 1 * 3600000).toISOString(),
    isResolved: false,
    source: 'manual',
    autoGenerated: false,
  },
  {
    id: 'sn_9',
    content: 'Alex Johnson checked in to Bed 101-A.',
    category: 'general',
    priority: 'normal',
    author: 'System',
    createdAt: new Date(today.getTime() - 48 * 3600000).toISOString(),
    isResolved: true,
    resolvedAt: new Date(today.getTime() - 48 * 3600000).toISOString(),
    source: 'checkin',
    relatedId: 'g_1',
    relatedType: 'guest',
    autoGenerated: true,
  },
  {
    id: 'sn_10',
    content: 'Bed 101-B marked as clean and ready.',
    category: 'general',
    priority: 'normal',
    author: 'System',
    createdAt: new Date(today.getTime() - 6 * 3600000).toISOString(),
    isResolved: true,
    resolvedAt: new Date(today.getTime() - 6 * 3600000).toISOString(),
    source: 'cleaning',
    relatedId: 'b_101_2',
    relatedType: 'bed',
    autoGenerated: true,
  },
];

export const INITIAL_GROUP_BOOKINGS: GroupBooking[] = [
  {
    id: 'gb_1',
    leaderName: "Marco's Surf Crew",
    source: 'direct',
    checkInDate: t(0),
    checkOutDate: t(3),
    memberIds: ['g_1', 'g_gb_1', 'g_gb_2', 'g_gb_3'],
    bedIds: ['b_101_7', 'b_101_8', 'b_102_3', 'b_102_4'],
    paymentMode: 'shared',
    totalAmount: 680,
    paidAmount: 340,
    notes: 'Surf crew — need board storage space.',
    createdAt: new Date(today.getTime() - 72 * 3600000).toISOString(),
  },
  {
    id: 'gb_2',
    leaderName: 'School Trip - Berlin',
    source: 'group',
    checkInDate: t(5),
    checkOutDate: t(8),
    memberIds: ['g_gb_4', 'g_gb_5', 'g_gb_6', 'g_gb_7', 'g_gb_8', 'g_gb_9'],
    bedIds: [],
    paymentMode: 'split',
    totalAmount: 1530,
    paidAmount: 0,
    notes: 'School group of 6 students. Need adjoining beds if possible.',
    createdAt: new Date(today.getTime() - 48 * 3600000).toISOString(),
  },
];

export const INITIAL_REFERRALS: Referral[] = [
  {
    id: 'ref_1',
    code: 'BUNKDESK-ALEX-3K7',
    referrerGuestId: 'g_1',
    referrerGuestName: 'Alex Johnson',
    usedByGuestIds: ['g_arr_1', 'g_gb_1'],
    reward: '10% off',
    commissionSaved: 68,
    createdAt: new Date(today.getTime() - 30 * 24 * 3600000).toISOString(),
  },
  {
    id: 'ref_2',
    code: 'BUNKDESK-SOPHIE-9M2',
    referrerGuestId: 'g_5',
    referrerGuestName: 'Sophie Martin',
    usedByGuestIds: ['g_arr_2'],
    reward: 'Free breakfast',
    commissionSaved: 25,
    createdAt: new Date(today.getTime() - 14 * 24 * 3600000).toISOString(),
  },
];

export const INITIAL_HOSTEL_PAGE: HostelPage = {
  id: 'hp_1',
  template: 'beach',
  hostelName: 'Sunset Backpackers',
  slug: 'sunset-backpackers',
  description: 'A chill beachside hostel with sunset views, surfboard rentals, and the best vibes in town.',
  coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=tropical%20beach%20hostel%20sunset%20palm%20trees%20backpackers&image_size=landscape_16_9',
  photos: [
    'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=surf%20hostel%20interior%20bunk%20beds%20bohemian%20decor&image_size=landscape_16_9',
    'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=dorm%20room%20beach%20vibe%20sunlight%20wooden%20bunks&image_size=landscape_16_9',
    'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=hostel%20common%20area%20hammocks%20tropical%20lounge&image_size=landscape_16_9',
  ],
  facilities: ['WiFi', 'Kitchen', 'Surfboard Rental', 'Locker', 'Laundry', 'Bar'],
  contactEmail: 'hello@sunsetbackpackers.com',
  contactPhone: '+1-555-0199',
  address: '123 Beach Road, Sunset Bay',
  published: true,
  updatedAt: new Date(today.getTime() - 7 * 24 * 3600000).toISOString(),
};

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 'promo_1',
    type: 'last-minute',
    name: 'Last Minute Deal!',
    discount: 20,
    startDate: t(0),
    endDate: t(3),
    active: true,
    createdAt: new Date(today.getTime() - 24 * 3600000).toISOString(),
  },
  {
    id: 'promo_2',
    type: 'long-stay',
    name: 'Stay 7+ Nights',
    discount: 15,
    startDate: t(7),
    endDate: t(30),
    minNights: 7,
    active: true,
    createdAt: new Date(today.getTime() - 48 * 3600000).toISOString(),
  },
];

export const INITIAL_GUEST_PROFILES: GuestProfile[] = [
  {
    id: 'gp_1',
    name: 'Marco Rossi',
    email: 'marco@gmail.com',
    whatsapp: '+39 333 1234567',
    country: 'Italy',
    countryCode: 'IT',
    gender: 'male',
    tags: ['digital-nomad', 'repeat-guest'],
    totalStays: 4,
    totalNights: 42,
    totalSpent: 3360,
    firstStayDate: '2025-03-15',
    lastStayDate: '2025-11-20',
  },
  {
    id: 'gp_2',
    name: 'Yuki Tanaka',
    email: 'yuki.tanaka@yahoo.co.jp',
    country: 'Japan',
    countryCode: 'JP',
    gender: 'female',
    tags: ['backpacker', 'repeat-guest'],
    totalStays: 2,
    totalNights: 10,
    totalSpent: 850,
    firstStayDate: '2025-06-01',
    lastStayDate: '2025-09-10',
  },
  {
    id: 'gp_3',
    name: 'Lena Müller',
    email: 'lena.m@web.de',
    whatsapp: '+49 170 9876543',
    country: 'Germany',
    countryCode: 'DE',
    gender: 'female',
    tags: ['long-stay', 'vip'],
    totalStays: 1,
    totalNights: 30,
    totalSpent: 2550,
    firstStayDate: '2025-08-01',
    lastStayDate: '2025-08-31',
  },
];
