export type BedStatus =
  | "empty"
  | "occupied"
  | "cleaning"
  | "reserved"
  | "late-arrival";

export type GuestSource = "walk-in" | "booking" | "airbnb" | "expedia" | "ical" | "manual" | "direct" | "referral" | "group";

export interface Guest {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  gender?: "male" | "female" | "other";
  checkInDate: string;
  checkOutDate: string;
  nights: number;
  paymentStatus: "paid" | "unpaid" | "partial";
  totalAmount?: number;
  paidAmount?: number;
  phone?: string;
  email?: string;
  notes?: string;
  passportScanned: boolean;
  passportOrId?: string;
  dob?: string;
  policeConsent?: boolean;
  source: GuestSource;
  roomPreference?: string;
  // ── 新增字段（2026-06-15 spec §6.1）──
  pinned?: boolean;          // 人工置顶
  assignedBedId?: string;    // 显式记录已分配床位
  notesSkipped?: boolean;    // 备注被显式跳过
}

export interface Bed {
  id: string;
  roomId: string;
  name: string; // e.g. "Bottom", "Top", "A", "B"
  bedType?: "top" | "bottom" | "single" | "double";
  status: BedStatus;
  guest?: Guest;
  reservations?: Guest[];
  cleaningAssignedTo?: string;
  cleaningStartedAt?: string;
  cleaningCompletedAt?: string;
  lastCleanedAt?: string;
}

export interface Room {
  id: string;
  number: string;
  name: string; // e.g. "Mixed Dorm", "Female Dorm", "Private Room"
  type: "dorm-mixed" | "dorm-female" | "private";
  pricePerNight: number; // Base price per night (top bunk for dorms, room price for private)
  bottomBunkPremium?: number; // Extra charge for bottom bunks (e.g. 10)
  beds: Bed[];
  floor: number;
}

// Staff
export type StaffRole = "reception" | "cleaning" | "manager";

export interface Staff {
  id: string;
  name: string;
  role: StaffRole;
  pin: string;
  phone?: string;
  isActive: boolean;
  createdAt: string;
}

// Shift Log
export type ShiftNoteCategory =
  | "general"
  | "late-arrival"
  | "maintenance"
  | "pickup"
  | "laundry"
  | "other";

export type ShiftNoteSource = "manual" | "checkin" | "checkout" | "cleaning" | "system";

export interface ShiftNote {
  id: string;
  content: string;
  category: ShiftNoteCategory;
  priority: "normal" | "urgent";
  author: string;
  assignee?: string;
  createdAt: string;
  resolvedAt?: string;
  isResolved: boolean;
  source: ShiftNoteSource;
  relatedId?: string;
  relatedType?: "guest" | "bed" | "room";
  autoGenerated: boolean;
}

// Group Booking
export type GroupPaymentMode = "shared" | "split";

export interface GroupBooking {
  id: string;
  leaderName: string;
  source: GuestSource;
  checkInDate: string;
  checkOutDate: string;
  memberIds: string[];       // Guest IDs
  bedIds: string[];          // Assigned bed IDs
  paymentMode: GroupPaymentMode;
  totalAmount: number;
  paidAmount: number;
  notes?: string;
  createdAt: string;
}

// Referral
export interface Referral {
  id: string;
  code: string;              // e.g. BUNKDESK-MARCO-7X2
  referrerGuestId: string;
  referrerGuestName: string;
  usedByGuestIds: string[];  // New guests who used this code
  reward: string;            // e.g. "10% off", "Free breakfast"
  commissionSaved: number;   // Estimated OTA commission saved
  createdAt: string;
}

// Hostel Page
export type HostelPageTemplate = "beach" | "city" | "nature";

export interface HostelPage {
  id: string;
  template: HostelPageTemplate;
  hostelName: string;
  slug: string;               // URL slug e.g. "sunset-hostel"
  description: string;
  coverImage: string;
  photos: string[];
  facilities: string[];       // e.g. ["WiFi", "Kitchen", "Locker"]
  contactEmail: string;
  contactPhone: string;
  address: string;
  mapLocation?: string;
  published: boolean;
  updatedAt: string;
}

// Promotion
export type PromotionType = "last-minute" | "early-bird" | "long-stay" | "group-discount";

export interface Promotion {
  id: string;
  type: PromotionType;
  name: string;
  discount: number;           // Percentage e.g. 15 = 15% off
  startDate: string;
  endDate: string;
  roomTypeFilter?: string;   // Apply to specific room type
  minNights?: number;        // For long-stay
  minGuests?: number;        // For group-discount
  active: boolean;
  createdAt: string;
}

// Guest CRM
export type GuestTag =
  | "digital-nomad"
  | "backpacker"
  | "long-stay"
  | "repeat-guest"
  | "vip"
  | "group-leader";

export interface GuestProfile {
  id: string;
  name: string;
  email?: string;
  phone?: string;
  whatsapp?: string;
  country: string;
  countryCode: string;
  gender?: "male" | "female" | "other";
  tags: GuestTag[];
  totalStays: number;
  totalNights: number;
  totalSpent: number;
  firstStayDate: string;
  lastStayDate: string;
  lastContactedAt?: string;
  notes?: string;
}

// Occupancy Actions
export type OccupancyActionType =
  | "long-stay-discount"
  | "old-guest-recall"
  | "last-minute-deal"
  | "room-type-conversion";

export interface OccupancyAction {
  id: string;
  type: OccupancyActionType;
  title: string;
  description: string;
  estimatedBedNights: number;
  estimatedRevenue: number;
  roomIds: string[];
  dateRange: { start: string; end: string };
  status: "pending" | "applied" | "dismissed";
  createdAt: string;
  appliedAt?: string;
  dismissedAt?: string;
}

// Guest Audit Log
// Phone number is the unique identifier that links a guest's history
// across multiple visits. A guest without a phone is logged by ID only
// and will not be linked to other visits.
export type GuestLogType =
  | "created"        // new arrival added
  | "check-in"       // assigned to a bed
  | "check-out"      // checked out
  | "payment"        // full or partial payment received
  | "charge"         // extra charge added to total
  | "note"           // note added / edited
  | "edit"           // profile field edited (name, phone, email, etc.)
  | "bed-change"     // moved to another bed
  | "extend-stay"    // stay lengthened
  | "shorten-stay"   // stay shortened
  | "scan-passport"  // passport scanned / unscanned
  | "reservation"    // reservation moved
  | "shift-note"     // linked shift note
  | "profile-merge"; // merged with another profile

export interface GuestLogEntry {
  id: string;
  phone: string;            // unique identifier for cross-visit linking
  guestId: string;          // the specific guest record this happened to
  guestName: string;        // snapshot at time of action
  type: GuestLogType;
  description: string;      // human-readable summary
  amount?: number;          // for payment / charge
  meta?: Record<string, any>;
  author: string;           // staff name (or 'system')
  createdAt: string;        // ISO timestamp
}

// Copilot Insights
export type InsightSeverity = "info" | "warning" | "opportunity" | "risk";

export interface CopilotInsight {
  id: string;
  type: "opportunity" | "risk" | "action";
  severity: InsightSeverity;
  title: string;
  description: string;
  actionLabel?: string;
  actionTarget?: string;
  relatedIds?: string[];
  createdAt: string;
  dismissed: boolean;
}
